apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-alpine
  template:
    metadata:
      labels:
        app: my-nginx-alpine
    spec:
      containers:
      - name: my-nginx-alpine
        image: jesmanto/my-nginx-alpine:1.0
        ports:
        - containerPort: 80
