apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  labels:
    app: my-nginx-alpine
spec:
  type: ClusterIP
  selector:
    app: my-nginx-alpine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

